server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  application:
    name: inventory-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    consumer:
      group-id: inventory-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.example.demo.dto.order.OrderCreatedEvent


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: localhost:${server.port}


logging:
  level:
    com:
      medical:
        service: TRACE
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
    root: INFO