server:
  port: 8085
spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.example.demo.dto.order.OrderCreatedEvent
logging:
  level:
    com:
      medical:
        service: TRACE
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: localhost:${server.port}
